[[constraint]]
  name = "github.com/msales/pkg"
  version = "1.*"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.*"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.*"
